### ISSUE TITLE
Wrong path in 'Setup network'

### ISSUE THREAD

**Issue by mjaco** [BrashEndeavours/bro-elk-IDS#1]
Under 'Setup network' - 'Setup the interfaces properly' the file path is wrong.

Should be: sudo bash -c 'cat > /etc/network/interfaces << EOL ... 
and not: sudo bash -c 'cat > /etc/udev/rules.d/70-persistent-net.rules << EOL ...

**Comment by unstable-deadlock** [comment]
Thanks for letting me know!

**Comment by mjaco** [comment]
:+1: No problem!
